### ISSUE TITLE
Are there any guide or wiki?

### ISSUE THREAD

**Issue by RobertWZ** [py0330/aris#21]
Great project,but there are no wiki or user guide.Can you write a wiki for stewart platform?

**Comment by py0330** [comment]
I'm sorry for not having enough time to update documentation of aris. I will make a stewart platform demo in next version. You can refer to http://106.15.224.250/dd/d40/dynamic_model_page.html to get some help.

**Comment by dbdxnuliba** [comment]
您好，http://106.15.224.250/dd/d40/dynamic_model_page.html 登陆不了 ，请问能解决下吗，谢谢
